language: ruby
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

rvm:
  - 2.4.1
services:
  - postgresql
