# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06e898d12838e985da03fd12a0911583c8004a10e7f88f3a60b60af839572da9652f5d59515d2f4f65c77c4272fa230d99aa61404b4fe83be424d68a4f6811b2

test:
  secret_key_base: a65ccbd7aa0cfb266f29230d8574f6cc7c2f9565322e75713bba72ec68813cbfbcd8aed8be76652c2624bef51455fc930869630fe13cf9faefcf7060f02de96c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
